"""
Text-to-Speech Module

Converts the generated podcast script into an MP3 audio file
using the OpenAI Text-to-Speech API.
"""

import os
from dotenv import load_dotenv
from openai import OpenAI


load_dotenv()

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY")
)


def generate_audio(script: str) -> str:
    """
    Convert podcast script into an MP3 audio file.

    Args:
        script (str): Podcast script generated by the LLM.

    Returns:
        str: Path to the generated MP3 file.
    """

    try:
        if not script:
            raise ValueError("No script provided for audio generation.")

        output_folder = "output"
        os.makedirs(output_folder, exist_ok=True)

        output_file = os.path.join(
            output_folder,
            "podcast.mp3"
        )

        response = client.audio.speech.create(
            model="tts-1",
            voice="alloy",
            input=script
        )

        response.stream_to_file(output_file)

        return output_file

    except Exception as e:
        print(f"TTS generation failed: {e}")
        return None